# Generated by Django 5.2.4 on 2025-07-28 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='assigned_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='assigned_team',
            field=models.CharField(blank=True, choices=[('TECH', 'Équipe Technique'), ('FINANCE', 'Équipe Financière'), ('SUPPORT', 'Support Client'), ('STATION', 'Agent de Station')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.JSONField(default=list, help_text="Liste des équipes auxquelles appartient l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent de station'), ('TECH', 'Technicien'), ('FINANCE', 'Agent Financier'), ('SUPPORT', 'Support Client'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=10),
        ),
    ]
