# Generated by Django 5.2.4 on 2025-08-02 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_reclamation_assigned_specialist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclamations.station', verbose_name='Station assignée'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent de station'), ('TECH', 'Technicien'), ('FINANCE', 'Agent Financier'), ('SUPPORT', 'Support Client'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=10, verbose_name='Rôle utilisateur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.JSONField(default=list, help_text="Liste des équipes auxquelles appartient l'utilisateur", verbose_name='Équipes assignées'),
        ),
    ]
