# Generated by Django 5.2.4 on 2025-08-03 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_alter_user_options_alter_reclamation_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ['-created_at'], 'permissions': [('can_take_charge', 'Peut prendre en charge les réclamations')], 'verbose_name': 'Réclamation', 'verbose_name_plural': 'Réclamations'},
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Agent assigné'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='assigned_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Spécialiste assigné'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='assigned_team',
            field=models.CharField(blank=True, choices=[('TECH', 'Équipe Technique'), ('FINANCE', 'Équipe Financière'), ('SUPPORT', 'Support Client'), ('STATION', 'Agent de Station')], max_length=20, null=True, verbose_name='Équipe responsable'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='contact_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Téléphone')], default='EMAIL', max_length=10, verbose_name='Méthode de contact préférée'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='description',
            field=models.TextField(verbose_name='Description du problème'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='estimated_resolution',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date estimée de résolution'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='incident_date',
            field=models.DateField(verbose_name="Date de l'incident"),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='incident_time',
            field=models.TimeField(verbose_name="Heure de l'incident"),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute')], default='MEDIUM', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='problem_type',
            field=models.CharField(choices=[('CARD_REJECTED', 'Carte rejetée lors du paiement'), ('CARD_BLOCKED', 'Carte bloquée/inactive'), ('BALANCE_ERROR', 'Solde incorrect'), ('RECHARGE_ISSUE', 'Recharge non reçue'), ('LIMIT_ISSUE', 'Problème de plafond'), ('LOST_STOLEN', 'Carte volée/perdue'), ('PAYMENT_REFUSED', 'Paiement refusé après utilisation'), ('DOUBLE_CHARGE', 'Double facturation'), ('DAMAGED_CARD', 'Carte endommagée'), ('DELIVERY_DELAY', 'Livraison en retard'), ('STATION_ISSUE', 'Problème technique en station'), ('FRAUD', 'Fraude suspectée'), ('OTHER', 'Autre problème')], max_length=20, verbose_name='Type de problème'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='requires_callback',
            field=models.BooleanField(default=False, verbose_name='Rappel demandé'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclamations.station', verbose_name='Station concernée'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
    ]
