# Generated by Django 5.2.4 on 2025-08-03 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0004_alter_reclamation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réclamation', 'verbose_name_plural': 'Réclamations'},
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='assigned_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='assigned_team',
            field=models.CharField(blank=True, choices=[('TECH', 'Équipe Technique'), ('FINANCE', 'Équipe Financière'), ('SUPPORT', 'Support Client'), ('STATION', 'Agent de Station')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='contact_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Téléphone')], default='EMAIL', max_length=10),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='incident_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='incident_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='problem_type',
            field=models.CharField(choices=[('CARD_REJECTED', 'Carte rejetée lors du paiement'), ('CARD_BLOCKED', 'Carte bloquée/inactive'), ('BALANCE_ERROR', 'Solde incorrect'), ('RECHARGE_ISSUE', 'Recharge non reçue'), ('LIMIT_ISSUE', 'Problème de plafond'), ('LOST_STOLEN', 'Carte volée/perdue'), ('PAYMENT_REFUSED', 'Paiement refusé après utilisation'), ('DOUBLE_CHARGE', 'Double facturation'), ('DAMAGED_CARD', 'Carte endommagée'), ('DELIVERY_DELAY', 'Livraison en retard'), ('STATION_ISSUE', 'Problème technique en station'), ('FRAUD', 'Fraude suspectée'), ('OTHER', 'Autre problème')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='requires_callback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclamations.station'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
