# Generated by Django 5.2.4 on 2025-08-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0005_alter_reclamation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': "Ce nom d'utilisateur est déjà utilisé."}, max_length=150, unique=True),
        ),
    ]
