# Generated by Django 5.2.4 on 2025-08-17 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0006_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approval_admin', models.BooleanField(default=True, help_text="Peut approuver les demandes d'inscription", verbose_name="Administrateur d'approbation")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Administrateur',
                'verbose_name_plural': 'Profils Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='InscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name="Nom d'utilisateur")),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent de station'), ('TECH', 'Technicien'), ('FINANCE', 'Agent Financier'), ('SUPPORT', 'Support Client'), ('ADMIN', 'Administrateur')], max_length=10, verbose_name='Rôle demandé')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': "Demande d'inscription",
                'verbose_name_plural': "Demandes d'inscription",
                'ordering': ['-created_at'],
                'permissions': [('can_approve_requests', 'Peut approuver les demandes')],
            },
        ),
    ]
