# Generated by Django 5.2.4 on 2025-08-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0007_adminprofile_inscriptionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionrequest',
            name='username',
            field=models.CharField(max_length=150, verbose_name="Nom d'utilisateur"),
        ),
    ]
